"""Added account table

Revision ID: 8eaedda8d928
Revises: 4811bb3a5f02
Create Date: 2022-06-28 21:00:56.031319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eaedda8d928'
down_revision = '4811bb3a5f02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coords_id'), 'coords', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('fam', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('otc', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('coords', sa.Integer(), nullable=True),
    sa.Column('beautyTitle', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('other_titles', sa.String(), nullable=True),
    sa.Column('connect', sa.String(), nullable=True),
    sa.Column('winter', sa.String(), nullable=True),
    sa.Column('summer', sa.String(), nullable=True),
    sa.Column('autumn', sa.String(), nullable=True),
    sa.Column('spring', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['coords'], ['coords.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passes_id'), 'passes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passes_id'), table_name='passes')
    op.drop_table('passes')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_coords_id'), table_name='coords')
    op.drop_table('coords')
    # ### end Alembic commands ###
